import "./globals.css";
import { Montserrat } from "next/font/google";
import { Header } from "./components/Header";

const font = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Job Search",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
